kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv
  labels:
    type: cluster
    name: sharedvolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/kube/hyperledger/shared

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: sharedvolume
